package com.yan.common.menu.mapper;

import com.yan.common.menu.model.TbSysMenu;
import com.yan.common.menu.model.TbSysMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbSysMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_MENU
     *
     * @mbg.generated Wed Sep 13 14:30:54 CST 2017
     */
    long countByExample(TbSysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_MENU
     *
     * @mbg.generated Wed Sep 13 14:30:54 CST 2017
     */
    int deleteByExample(TbSysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_MENU
     *
     * @mbg.generated Wed Sep 13 14:30:54 CST 2017
     */
    int deleteByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_MENU
     *
     * @mbg.generated Wed Sep 13 14:30:54 CST 2017
     */
    int insert(TbSysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_MENU
     *
     * @mbg.generated Wed Sep 13 14:30:54 CST 2017
     */
    int insertSelective(TbSysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_MENU
     *
     * @mbg.generated Wed Sep 13 14:30:54 CST 2017
     */
    List<TbSysMenu> selectByExample(TbSysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_MENU
     *
     * @mbg.generated Wed Sep 13 14:30:54 CST 2017
     */
    TbSysMenu selectByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_MENU
     *
     * @mbg.generated Wed Sep 13 14:30:54 CST 2017
     */
    int updateByExampleSelective(@Param("record") TbSysMenu record, @Param("example") TbSysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_MENU
     *
     * @mbg.generated Wed Sep 13 14:30:54 CST 2017
     */
    int updateByExample(@Param("record") TbSysMenu record, @Param("example") TbSysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_MENU
     *
     * @mbg.generated Wed Sep 13 14:30:54 CST 2017
     */
    int updateByPrimaryKeySelective(TbSysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_MENU
     *
     * @mbg.generated Wed Sep 13 14:30:54 CST 2017
     */
    int updateByPrimaryKey(TbSysMenu record);
}