package com.yan.common.user.mapper;

import com.yan.common.user.model.TbSysUser;
import com.yan.common.user.model.TbSysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_USER
     *
     * @mbg.generated Wed Sep 13 14:28:39 CST 2017
     */
    long countByExample(TbSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_USER
     *
     * @mbg.generated Wed Sep 13 14:28:39 CST 2017
     */
    int deleteByExample(TbSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_USER
     *
     * @mbg.generated Wed Sep 13 14:28:39 CST 2017
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_USER
     *
     * @mbg.generated Wed Sep 13 14:28:39 CST 2017
     */
    int insert(TbSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_USER
     *
     * @mbg.generated Wed Sep 13 14:28:39 CST 2017
     */
    int insertSelective(TbSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_USER
     *
     * @mbg.generated Wed Sep 13 14:28:39 CST 2017
     */
    List<TbSysUser> selectByExample(TbSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_USER
     *
     * @mbg.generated Wed Sep 13 14:28:39 CST 2017
     */
    TbSysUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_USER
     *
     * @mbg.generated Wed Sep 13 14:28:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") TbSysUser record, @Param("example") TbSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_USER
     *
     * @mbg.generated Wed Sep 13 14:28:39 CST 2017
     */
    int updateByExample(@Param("record") TbSysUser record, @Param("example") TbSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_USER
     *
     * @mbg.generated Wed Sep 13 14:28:39 CST 2017
     */
    int updateByPrimaryKeySelective(TbSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_USER
     *
     * @mbg.generated Wed Sep 13 14:28:39 CST 2017
     */
    int updateByPrimaryKey(TbSysUser record);
}